// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobRepositoryInterface creates a new instance of MockJobRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepositoryInterface {
	mock := &MockJobRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobRepositoryInterface is an autogenerated mock type for the JobRepositoryInterface type
type MockJobRepositoryInterface struct {
	mock.Mock
}

type MockJobRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepositoryInterface) EXPECT() *MockJobRepositoryInterface_Expecter {
	return &MockJobRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) Create(job *models.Job) error {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Job) error); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJobRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - job *models.Job
func (_e *MockJobRepositoryInterface_Expecter) Create(job interface{}) *MockJobRepositoryInterface_Create_Call {
	return &MockJobRepositoryInterface_Create_Call{Call: _e.mock.On("Create", job)}
}

func (_c *MockJobRepositoryInterface_Create_Call) Run(run func(job *models.Job)) *MockJobRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Job
		if args[0] != nil {
			arg0 = args[0].(*models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_Create_Call) Return(err error) *MockJobRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepositoryInterface_Create_Call) RunAndReturn(run func(job *models.Job) error) *MockJobRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJobRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockJobRepositoryInterface_Expecter) Delete(id interface{}) *MockJobRepositoryInterface_Delete_Call {
	return &MockJobRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockJobRepositoryInterface_Delete_Call) Run(run func(id string)) *MockJobRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_Delete_Call) Return(err error) *MockJobRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepositoryInterface_Delete_Call) RunAndReturn(run func(id string) error) *MockJobRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganizedOlderThan provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) DeleteOrganizedOlderThan(date time.Time) error {
	ret := _mock.Called(date)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizedOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(date)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganizedOlderThan'
type MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call struct {
	*mock.Call
}

// DeleteOrganizedOlderThan is a helper method to define mock.On call
//   - date time.Time
func (_e *MockJobRepositoryInterface_Expecter) DeleteOrganizedOlderThan(date interface{}) *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call {
	return &MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call{Call: _e.mock.On("DeleteOrganizedOlderThan", date)}
}

func (_c *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call) Run(run func(date time.Time)) *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call) Return(err error) *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call) RunAndReturn(run func(date time.Time) error) *MockJobRepositoryInterface_DeleteOrganizedOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) FindByID(id string) (*models.Job, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Job, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Job); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockJobRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id string
func (_e *MockJobRepositoryInterface_Expecter) FindByID(id interface{}) *MockJobRepositoryInterface_FindByID_Call {
	return &MockJobRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockJobRepositoryInterface_FindByID_Call) Run(run func(id string)) *MockJobRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_FindByID_Call) Return(job *models.Job, err error) *MockJobRepositoryInterface_FindByID_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobRepositoryInterface_FindByID_Call) RunAndReturn(run func(id string) (*models.Job, error)) *MockJobRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) List() ([]models.Job, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Job, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Job); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockJobRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockJobRepositoryInterface_Expecter) List() *MockJobRepositoryInterface_List_Call {
	return &MockJobRepositoryInterface_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockJobRepositoryInterface_List_Call) Run(run func()) *MockJobRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobRepositoryInterface_List_Call) Return(jobs []models.Job, err error) *MockJobRepositoryInterface_List_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobRepositoryInterface_List_Call) RunAndReturn(run func() ([]models.Job, error)) *MockJobRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) Update(job *models.Job) error {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Job) error); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockJobRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - job *models.Job
func (_e *MockJobRepositoryInterface_Expecter) Update(job interface{}) *MockJobRepositoryInterface_Update_Call {
	return &MockJobRepositoryInterface_Update_Call{Call: _e.mock.On("Update", job)}
}

func (_c *MockJobRepositoryInterface_Update_Call) Run(run func(job *models.Job)) *MockJobRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Job
		if args[0] != nil {
			arg0 = args[0].(*models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_Update_Call) Return(err error) *MockJobRepositoryInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepositoryInterface_Update_Call) RunAndReturn(run func(job *models.Job) error) *MockJobRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockJobRepositoryInterface
func (_mock *MockJobRepositoryInterface) Upsert(job *models.Job) error {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Job) error); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobRepositoryInterface_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockJobRepositoryInterface_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - job *models.Job
func (_e *MockJobRepositoryInterface_Expecter) Upsert(job interface{}) *MockJobRepositoryInterface_Upsert_Call {
	return &MockJobRepositoryInterface_Upsert_Call{Call: _e.mock.On("Upsert", job)}
}

func (_c *MockJobRepositoryInterface_Upsert_Call) Run(run func(job *models.Job)) *MockJobRepositoryInterface_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Job
		if args[0] != nil {
			arg0 = args[0].(*models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobRepositoryInterface_Upsert_Call) Return(err error) *MockJobRepositoryInterface_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobRepositoryInterface_Upsert_Call) RunAndReturn(run func(job *models.Job) error) *MockJobRepositoryInterface_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
