// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/javinizer/javinizer-go/internal/config"
	"github.com/javinizer/javinizer-go/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScraper creates a new instance of MockScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScraper {
	mock := &MockScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScraper is an autogenerated mock type for the Scraper type
type MockScraper struct {
	mock.Mock
}

type MockScraper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScraper) EXPECT() *MockScraper_Expecter {
	return &MockScraper_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockScraper
func (_mock *MockScraper) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScraper_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockScraper_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockScraper_Expecter) Close() *MockScraper_Close_Call {
	return &MockScraper_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockScraper_Close_Call) Run(run func()) *MockScraper_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraper_Close_Call) Return(err error) *MockScraper_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScraper_Close_Call) RunAndReturn(run func() error) *MockScraper_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockScraper
func (_mock *MockScraper) Config() *config.ScraperSettings {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.ScraperSettings
	if returnFunc, ok := ret.Get(0).(func() *config.ScraperSettings); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ScraperSettings)
		}
	}
	return r0
}

// MockScraper_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockScraper_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockScraper_Expecter) Config() *MockScraper_Config_Call {
	return &MockScraper_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockScraper_Config_Call) Run(run func()) *MockScraper_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraper_Config_Call) Return(scraperConfig *config.ScraperSettings) *MockScraper_Config_Call {
	_c.Call.Return(scraperConfig)
	return _c
}

func (_c *MockScraper_Config_Call) RunAndReturn(run func() *config.ScraperSettings) *MockScraper_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type MockScraper
func (_mock *MockScraper) GetURL(id string) (string, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScraper_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockScraper_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - id string
func (_e *MockScraper_Expecter) GetURL(id interface{}) *MockScraper_GetURL_Call {
	return &MockScraper_GetURL_Call{Call: _e.mock.On("GetURL", id)}
}

func (_c *MockScraper_GetURL_Call) Run(run func(id string)) *MockScraper_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScraper_GetURL_Call) Return(s string, err error) *MockScraper_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockScraper_GetURL_Call) RunAndReturn(run func(id string) (string, error)) *MockScraper_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type MockScraper
func (_mock *MockScraper) IsEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockScraper_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockScraper_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
func (_e *MockScraper_Expecter) IsEnabled() *MockScraper_IsEnabled_Call {
	return &MockScraper_IsEnabled_Call{Call: _e.mock.On("IsEnabled")}
}

func (_c *MockScraper_IsEnabled_Call) Run(run func()) *MockScraper_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraper_IsEnabled_Call) Return(b bool) *MockScraper_IsEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockScraper_IsEnabled_Call) RunAndReturn(run func() bool) *MockScraper_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockScraper
func (_mock *MockScraper) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockScraper_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockScraper_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockScraper_Expecter) Name() *MockScraper_Name_Call {
	return &MockScraper_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockScraper_Name_Call) Run(run func()) *MockScraper_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScraper_Name_Call) Return(s string) *MockScraper_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockScraper_Name_Call) RunAndReturn(run func() string) *MockScraper_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockScraper
func (_mock *MockScraper) Search(id string) (*models.ScraperResult, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *models.ScraperResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ScraperResult, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ScraperResult); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ScraperResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScraper_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockScraper_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - id string
func (_e *MockScraper_Expecter) Search(id interface{}) *MockScraper_Search_Call {
	return &MockScraper_Search_Call{Call: _e.mock.On("Search", id)}
}

func (_c *MockScraper_Search_Call) Run(run func(id string)) *MockScraper_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScraper_Search_Call) Return(scraperResult *models.ScraperResult, err error) *MockScraper_Search_Call {
	_c.Call.Return(scraperResult, err)
	return _c
}

func (_c *MockScraper_Search_Call) RunAndReturn(run func(id string) (*models.ScraperResult, error)) *MockScraper_Search_Call {
	_c.Call.Return(run)
	return _c
}
